package com.lucasian.cargueadministradoras.modelo;
// Generated 28/04/2019 12:24:30 AM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * Administradora generated by hbm2java
 */
public class Administradora  implements java.io.Serializable {


     private Long id;
     private String codigo;
     private String nombre;
     private String codTpId;
     private String nroId;
     private String naturaleza;
     private Long multipleArp;
     private Long fsp;
     private Long fusionada;
     private Date fechaFusion;

    public Administradora() {
    }

	
    public Administradora(Long id, String codigo, String nombre, String codTpId, String nroId, String naturaleza, Long multipleArp, Long fsp, Long fusionada) {
        this.id = id;
        this.codigo = codigo;
        this.nombre = nombre;
        this.codTpId = codTpId;
        this.nroId = nroId;
        this.naturaleza = naturaleza;
        this.multipleArp = multipleArp;
        this.fsp = fsp;
        this.fusionada = fusionada;
    }
    public Administradora(Long id, String codigo, String nombre, String codTpId, String nroId, String naturaleza, Long multipleArp, Long fsp, Long fusionada, Date fechaFusion) {
       this.id = id;
       this.codigo = codigo;
       this.nombre = nombre;
       this.codTpId = codTpId;
       this.nroId = nroId;
       this.naturaleza = naturaleza;
       this.multipleArp = multipleArp;
       this.fsp = fsp;
       this.fusionada = fusionada;
       this.fechaFusion = fechaFusion;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodTpId() {
        return this.codTpId;
    }
    
    public void setCodTpId(String codTpId) {
        this.codTpId = codTpId;
    }
    public String getNroId() {
        return this.nroId;
    }
    
    public void setNroId(String nroId) {
        this.nroId = nroId;
    }
    
    public String getNaturaleza() {
    	return this.naturaleza;
    }
    public void setNaturaleza(String naturaleza) {
    	this.naturaleza = naturaleza;
    }
    
    public Long getMultipleArp() {
        return this.multipleArp;
    }
    
    public void setMultipleArp(Long multipleArp) {
        this.multipleArp = multipleArp;
    }
    public Long getFsp() {
        return this.fsp;
    }
    
    public void setFsp(Long fsp) {
        this.fsp = fsp;
    }
    public Long getFusionada() {
        return this.fusionada;
    }
    
    public void setFusionada(Long fusionada) {
        this.fusionada = fusionada;
    }
    public Date getFechaFusion() {
        return this.fechaFusion;
    }
    
    public void setFechaFusion(Date fechaFusion) {
        this.fechaFusion = fechaFusion;
    }

}


